---
title:  "JAVA 스터디 9주차"
excerpt: "자바의 예외 처리"

categories:
  - Java
  - 스터디
tags:
  - Java
last_modified_at: 2021-05-13T08:22:00-05:00
---


# 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)

## try-catch-finally

- 예외 처리를 위해 `try-catch` 구문을 이용한다.
```java
try {
  // 예외 발생 가능성이 있는 코드 작성
} catch (Exception1 e1) {
  // Exception1 예외 발생 후 처리하는 코드 작성
  try {
    // catch 블럭 중 또 다시 예외 발생 가능성이 있는 코드 작성
  } catch (Exception5 e5) {
    // 이 때 Exception5 의 변수명을 e1 으로 하면 오류가 난다.
  }
} catch (Exception2 | Exception3 e) {
  // 이런식으로 여러 catch 블록을 하나로 작성도 가능하다 (multi catch 구문)
  // Exception2, Exception3 예외 발생 후 처리하는 코드 작성 
} catch (Exception4 e4 {
  // Exception4 예외 발생 후 처리하는 코드 작성  
} finally {
  // 예외 발생 여부와 상관없이 무조건 실행하는 코드
}
```

## throw

- `throw` 키워드를 이용해 고의로 예외를 발생 시킬 수도 있다.

```java
...
if (nameInput.getName().equals("whiteship")) {
  throw new IllegalArgumentException("name 인자가 부적절 합니다.");
}
// throw new IllegalArgumentException("name 인자가 부적절 합니다."); 는 아래 소스와 같다.
// IllegalArgumentException e = new IllegalArgumentException("name 인자가 부적절 합니다.");
// throw e;
...
```

## throws

- `throws` 키워드를 통해 메소드에 예외를 선언할 수 있다.

- `throws` 자체는 예외 처리가 아니다. 해당 메소드를 사용할 때 이를 사용하는 곳에서 예외 처리를 하도록 책임을 전가하는 역할을 한다.

```java
void myMethod1(int num) {
  try {
    if (num < 0>) {
      throw new Exception1("0보다 작다.");
    } elif (num == 0) {
      throw new Exception2("0이다.");
    }
  } catch (Exception1 e1) {
    e1.getMessage();
  } catch (Exception2 e2) {
    e2.getMessage();
  }
  log.info("숫자는 " + num);
}

void myMethod2() {
  int i = 10;
  myMethod1(i);

}

// thorws 사용 예제 1
void myThrowsMethod1(int num) throws Exception1, Exception2 {
  if (num < 0>) {
    throw new Exception1("0보다 작다.");
  } elif (num == 0) {
    throw new Exception2("0이다.");
  }
  log.info("숫자는 " + num);
}

void myMethod2() {
  int i = 0;
  try {
    myThrowsMethod1(i); // myThrowsMethod1 을 사용했기에 예외처리를 해야한다.
  } catch (Exception1 e1) {
    // something..
  } catch (Exception2 e2) {
    // something..
  }
}

// thorws 사용 예제 2
void myThrowsMethod1(int num) throws Exception1, Exception2 {
  if (num < 0>) {
    throw new Exception1("0보다 작다.");
  } elif (num == 0) {
    throw new Exception2("0이다.");
  }
  log.info("숫자는 " + num);
}

void myMethod2() throws Exception1, Exception2 {
  int i = 0;
  myThrowsMethod1(i);
}
```


# 자바가 제공하는 예외 계층 구조

![image](https://user-images.githubusercontent.com/25449640/118127319-7f2eba80-b434-11eb-8375-158988a51d0a.png)

(출처 : https://wisdom-and-record.tistory.com/46)

- `Exception` 과 `Error` 가 `Throwable` 클래스를 상속받고 있다. 

- 이중에서 `Throwable` 의 `RuntimeException` 을 제외한 나머지 클래스는 `Checked Exception` 이다. 이는 컴파일 시에 체크가 된다.

- `RuntimeException` 클래스는 `Unchecked Exception` 이다. 컴파일 시에 잡아낼 수 없다.


# Exception과 Error의 차이는?

## Exception

- 컴퓨터의 에러가 아닌 사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인해 발생하는 오류.

- 예외처리를 통해 프로그램이 종료가 되는것을 막을 수 있다.

- `Checked Exception` 과 `Unchecked Exception` 으로 나눌 수 있다.

- 쓰레드에 영향을 끼친다.

## Error

- 컴퓨터의 하드웨어 오동작 또는 고장 등으로 인해 프로그램에 문제가 생겼거나 JVM 실행에 문제가 생겼을 때 발생하는 오류.

- 프로세스에 영향을 끼친다.

- `OutOfMemoryError`, `StackOverflowError`, `VirtualMachineError` 등.


# RuntimeException과 RE가 아닌 것의 차이는?

- 위에서 말한 `Checked Exception` 과 `Unchecked Exception` 을 나누는 기준이다.

- `RuntimeException` 은 `Unchecked Exception` 이고 그 외의 예외는 `Checked Exception` 이다.

- `Checked Exception` 은 컴파일 시에 검사가 되지만 `RuntimeException` 은 예외를 미리 감지하지 못한다.


# 커스텀한 예외 만드는 방법

- `Exception` 과 `Error` 모두 `Throwable` 클래스를 상속받은 클래스 들이다. 우리는 이 중에 `Exception` 클래스를 상속받은 클래스로 커스텀 예외 클래스를 만들어야 한다.

- `Error` 클래스는 하드웨어와 관련된 예외이기 때문이다.

```java
class MyException extends Exception {
  public MyExcpetion(String errorMessage) {
    super(errorMessage); // Exception 의 생성자 호출
  }
}
```